"""Оркестратор развёртывания (FR-C6 bonus).

Рендерит профиль ловушки в самодостаточный артефакт:
  - docker-compose snippet + Dockerfile для контейнерной ловушки;
  - install.sh — установка агента как systemd-сервиса на удалённый хост.

Доставка на хост выполняется оператором/CI (scp/ssh); центр генерирует артефакт
и отдаёт его по API одной кнопкой. Секрет агента попадает только в env-файл на хосте.
"""
from __future__ import annotations

import json
from typing import Any

DOCKERFILE = """FROM python:3.12-slim
WORKDIR /opt/svc
COPY honeyd.py ./
RUN useradd -r -s /usr/sbin/nologin svcmon
USER svcmon
ENTRYPOINT ["python3", "honeyd.py"]
"""


def render_agent_config(profile: dict[str, Any], trap_uuid: str) -> dict[str, Any]:
    """Конфиг агента. Никаких слов honeypot/C2 внутри — только 'telemetry endpoint'."""
    return {
        "node_id": trap_uuid,
        "endpoint": profile.get("masking", {}).get("cover_path", "/static/js/analytics.js"),
        "interval": profile.get("masking", {}).get("beacon_interval_sec", 45),
        "jitter_pct": profile.get("masking", {}).get("beacon_jitter_pct", 35),
        "profile": profile,
    }


def render_compose_bundle(trap_name: str, trap_uuid: str, center_url: str,
                          profile: dict[str, Any]) -> dict[str, str]:
    """Возвращает файлы артефакта развёртывания {имя: содержимое}."""
    slug = "".join(c if c.isalnum() else "-" for c in trap_name.lower()).strip("-")
    ports = [int(s["port"]) for s in profile.get("services", [])]
    cfg = render_agent_config(profile, trap_uuid)
    compose = f"""version: "3.9"
# Auto-generated by HoneyForge orchestrator — trap '{trap_name}'
services:
  {slug}:
    build: .
    container_name: {slug}
    restart: unless-stopped
    network_mode: host            # эмуляция сервисов напрямую на портах хоста
    cap_drop: [ALL]
    security_opt: ["no-new-privileges:true"]
    environment:
      HFD_CENTER_URL: "{center_url}"
      HFD_CONFIG_B64: "{{{{HFD_CONFIG_B64}}}}"   # подставить из env-файла при деплое
      HF_TRAP_UUID: "{trap_uuid}"
"""
    install_sh = f"""#!/bin/sh
# Деплой ловушки '{trap_name}' на удалённый хост (выполнить на хосте DMZ)
set -e
mkdir -p /opt/svc-{slug} && cd /opt/svc-{slug}
cp honeyd.py Dockerfile docker-compose.yml . 2>/dev/null || true
# Секрет и конфиг кладём в env-файл (не в код): chmod 600
cat > /etc/hf-node.env <<ENVEOF
HF_TRAP_UUID={trap_uuid}
HFD_SECRET={{AGENT_SECRET}}
HFD_CENTER_URL={center_url}
ENVEOF
chmod 600 /etc/hf-node.env
docker compose up -d --build
"""
    return {
        "docker-compose.yml": compose,
        "Dockerfile": DOCKERFILE,
        "install.sh": install_sh,
        "agent-config.json": json.dumps(cfg, indent=2, ensure_ascii=False),
        "_ports": ",".join(map(str, ports)),
    }
